# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'watchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Charts'
  pod 'JSQMessagesViewController'
  target 'watchAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'watchApp WatchKit App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchApp WatchKit App

end

target 'watchApp WatchKit Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchApp WatchKit Extension

end
